name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Generate sign key
      env:
        TEST_KEY:  ${{secrets.TEST_KEY}}
      run: |
          echo "$TEST_KEY" | base64 --decode > test.kts && sha1sum test.kts
